# Generated by Django 4.1.1 on 2022-09-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('snippet_title', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snippet_title_01', models.CharField(blank=True, default='', max_length=100)),
                ('snippet_01', models.TextField(blank=True)),
                ('snippet_description_01', models.TextField(blank=True)),
                ('snippet_title_02', models.CharField(blank=True, default='', max_length=100)),
                ('snippet_02', models.TextField(blank=True)),
                ('snippet_description_02', models.TextField(blank=True)),
                ('snippet_title_03', models.CharField(blank=True, default='', max_length=100)),
                ('snippet_03', models.TextField(blank=True)),
                ('snippet_description_03', models.TextField(blank=True)),
                ('snippet_title_04', models.CharField(blank=True, default='', max_length=100)),
                ('snippet_04', models.TextField(blank=True)),
                ('snippet_description_04', models.TextField(blank=True)),
            ],
        ),
    ]
