# Generated by Django 4.1.1 on 2022-09-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='snippet_title',
            new_name='snippet_description',
        ),
    ]
