# Generated by Django 4.1.1 on 2022-09-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_snippet_title_notes_snippet_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='snippet_description',
        ),
    ]
