# Generated by Django 4.1.3 on 2022-12-16 05:28

import apps.contacts_book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=250)),
                ("last_name", models.CharField(blank=True, max_length=250)),
                ("twitter_handle", models.CharField(blank=True, max_length=250)),
                ("avatar_url", models.TextField(blank=True)),
                (
                    "avatar_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.contacts_book.models.user_directory_path,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("favorite", models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
