# Generated by Django 4.0.5 on 2022-06-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='name',
            field=models.CharField(default='Gajendrasingh dawar', max_length=200),
        ),
    ]
